# Generated by Django 2.2.2 on 2019-07-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30, verbose_name='Teacher Name')),
                ('teacher_salary', models.FloatField(max_length=5, verbose_name='Salary')),
            ],
        ),
        
    ]
