# Generated by Django 2.2.2 on 2019-07-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_library_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
    ]
