# Generated by Django 2.2.2 on 2019-07-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_teacher',
        ),
    ]
