# Generated by Django 2.2.2 on 2019-07-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190702_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(default=None, null=True, to='home.Teacher'),
        ),
    ]
