# Generated by Django 2.2.2 on 2019-07-02 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_student_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=50, null=True, verbose_name='Subject Taught'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='borrowed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student', verbose_name='Borrowed By'),
        ),
        migrations.AlterModelTable(
            name='library',
            table='BookInfo',
        ),
        migrations.AlterModelTable(
            name='student',
            table='StudentInfo',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='TeacherInfo',
        ),
    ]
