# Generated by Django 2.2.2 on 2019-07-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=None, null=True, upload_to='student'),
        ),
    ]
